### Nucleotide chains in their respective amino acids ###
## These arrays are used in 'main.py' to process output ##

F = ["UUU", "UUC"]
L = ["UUG", "UUA", "CUU", "CUC", "CUA", "CUG"]
I = ["AUU", "AUC", "AUA"]
M = ["AUG"]
V = ["GUU", "GUC", "GUA", "GUG"]
S = ["UCU", "UCC", "UCA", "UCG", "AGC", "AGU"]
P = ["CCU", "CCC", "CCA", "CCG"]
T = ["ACG", "ACA", "ACC", "ACU"]
A = ["GCU", "GCC", "GCA", "GCG"]
Y = ["UAC", "UAU"]
H = ["CAC", "CAU"]
Q = ["CAA", "CAG"]
N = ["AAC", "AAU"]
K = ["AAA", "AAG"]
D = ["GAU", "GAC"]
E = ["GAA", "GAG"]
C = ["UGU", "UGC"]
W = ["UGG"]
R = ["CGG", "CGA", "CGC", "CGU", "AGG", "AGA"]
G = ["GGG", "GGA", "GGC", "GGU"]
STP = ["UAA", "UAG", "UGA"]
STR = ["AUG"]
