### Nucleotide chains in their respective amino acids ###
## These arrays are used in 'main.py' to process output ##

F = ["TTT", "TTC"]
L = ["TTA", "TTG"]
S = ["TCT", "TCC", "TCA", "TCG", "AGC", "AGT"]
Y = ["TAT", "TAC"]
C = ["TGT", "TGC"]
W = ["TGG"]
P = ["CCT", "CCC", "CCA", "CCG"]
H = ["CAT", "CAC"]
Q = ["CAG", "CAA"]
R = ["CGG", "CGA", "CGC", "CGT"]
I = ["ATT", "ATC", "ATA"]
M = ["ATG"]
T = ["ACT", "ACC", "ACA", "ACG"]
N = ["AAC", "AAT"]
K = ["AAA", "AAG"]
V = ["GTT", "GTC", "GTA", "GTG"]
A = ["GCT", "GCC", "GCA", "GCG"]
D = ["GAT", "GAC"]
E = ["GAA", "GAG"]
G = ["GGT", "GGC", "GGA", "GGG"]
STR = ["ATG"]
STP = ["TAA", "TAG", "TGA"]